---
kind: "operation"
client: "rug-cli 0.28.0"
generator:
  name: "NewStarterRugProject"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.20.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-editors.git"
    branch: "9155568aae57327518bc4f6b31c2ee3793c2773e"
    sha: "9155568"
  parameters:
    - "project_name": "kubernetes-handlers"

---
kind: "operation"
client: "rug-cli 1.0.0-m.1"
editor:
  name: "UpdateSupportFiles"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.29.0"
  origin:
    repo: "https://github.com/atomist/rug-rugs.git"
    branch: "0f425945c62957ccc2ccb63e9980e6f78b97a4a1"
    sha: "0f42594"

